### ISSUE TITLE
DDoS - Could not finish initialization, retrying... retrying... retrying... retrying... retrying...

### ISSUE THREAD

**Issue by holgerpieta** [virtualzone/landroid-bridge#100]
Unfortunately #86 still doesn't seem to be fixed. But I cannot reopen the ticket, so here is a new one.
If you want, please reopen the other ticket and close this as a duplicate.

Retrying happens a lot slower now, so less danger of getting banned, but it still doesn't work.

Relevant part from the logs:
`[2020-06-07T13:41:11.155] [INFO] LandroidS - Initializing Landroid Cloud Service...`
`[2020-06-07T13:41:11.231] [INFO] Mqtt - Successfully connected to MQTT Broker!
Mqtt url: undefined`
`[2020-06-07T13:41:14.871] [INFO] IoBrokerAdapter - mower 0 selected`
`[2020-06-07T13:41:57.567] [INFO] Mqtt - Incoming MQTT message to topic landroid/set/poll: b37842b1.1d2468`
`[2020-06-07T13:41:57.569] [INFO] LandroidS - Sending to landroid cloud: {}`
`[2020-06-07T13:42:11.157] [INFO] LandroidS - Could not finish initialization, retrying...
Mqtt url: undefined`
`[2020-06-07T13:42:12.852] [INFO] IoBrokerAdapter - mower 0 selected`

I'll try to dig into that and find the problem, but if someone knows where to look, that would be helpful.

**Comment by holgerpieta** [comment]
Erm, ok, I think I found the problem: The images on docker hub are created on 11-04-2020, but the required changes have been committed on 15-04-2020.
So I guess the maintainer just needs to recreate the images.

**Comment by virtualzone** [comment]
I see, automated build at Docker Hub didn't succeed: 

```
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/MeisterTR/ioBroker.landroid-s.git
```

Seems like builds on Docker Hub can't run Git. I'll try to find a solution.

**Comment by holgerpieta** [comment]
Oh, nice...erm, not nice. Interesting problem.

In the meantime, for everybody using a Raspi or any other arm32v7 device: thewaldschrat/landroid-bridge

**Comment by virtualzone** [comment]
@holgerpieta git was missing in the Docker build environment. Just fixed that, new images are building right now. Should be fixed shortly. Thanks for your hint!

**Comment by holgerpieta** [comment]
Took a while for Docker Hub to build the image, but now I can report: arm32v7 is working correctly!

**Comment by virtualzone** [comment]
Great, thanks for your feedback!
