### ISSUE TITLE
MQTT: SSL/TLS

### ISSUE THREAD

**Issue by webcharlyx** [virtualzone/landroid-bridge#43]
Would it be / is it possible to use TLS or SSL on the MQTT connection? 
username and strong password is already helpful but not secure in the end #27

**Comment by Hooch76** [comment]
I would also like to be able to use MQTT with TLS/SSL. Any chance that this could be implemented?

**Comment by virtualzone** [comment]
I've added support for TLS/SSL, including client certificates. Please check the updated readme.

**Comment by webcharlyx** [comment]
@virtualzone THX for implementing!
tried it on latest docker version.
sorry, can't find any hints on the log, why it is **not** using the TLS/SSL, but still the unencrypted.
BTW would an option to pass a password for client key be possible in general?
