### ISSUE TITLE
virtualzone/landroid-bridge:arm32v7 - "exec format error"

### ISSUE THREAD

**Issue by nicoh88** [virtualzone/landroid-bridge#72]
Hi, 

the docker-container for rpi (arm32v7) doesn't work. 

```
cat /proc/device-tree/model
Raspberry Pi 3 Model B Rev 1.2
```

If start the docker-container gets an error:

`standard_init_linux.go:207: exec user process caused "exec format error"`

_No more and no less!_ 😢 

---

```
docker run \
    -p 3000:3000 \
    --name landroid_bridge \
    --link mqtt:mqtt \
    -v /tmp/config.json:/usr/src/app/config.json \
    virtualzone/landroid-bridge:arm32v7
```

---

What can i do? 😕 

---

**EDIT1:**

`weweave/landroid-bridge:arm32v7` starts successfully, but use the old api.

**Comment by pilip87** [comment]
same error for me

**Comment by pilip87** [comment]
anyone can help?

**Comment by avanc** [comment]
I'm also strugeling with this error.
For another docker, I'm using the arm32v8 build. Does this makes any differences on an Raspi 3B+

**Comment by avanc** [comment]
I tried to build the image by myself using https://github.com/virtualzone/landroid-bridge/blob/master/build-arm32v7.sh.
Instead of using `arm32v7/node:11` I used `arm32v6/node:12-alpine` and it works without problems.
