### ISSUE TITLE
IP blocked due to use of unofficial app

### ISSUE THREAD

**Issue by rjwonder** [virtualzone/landroid-bridge#84]
My IP got blocked by Worx for using a non official app. Consequence is that I can't use the official app or the Landroid bridge anymore from my home wifi (without requesting a new IP or go VPN). Still works on 4g.

As this is the only non-official software I'm using, it might be good for others to be aware of it.

**Comment by rjwonder** [comment]
Update: I'm unblocked (auto within X hours?) and can use the app again from wifi

**Comment by riker09** [comment]
I believe I've read somewhere that the ban usually lasts for 24 hours.

**Comment by int5749** [comment]
Yes, once the "issue" has been solved/removed, it took 24h to get unblocked
