### ISSUE TITLE
Newbie, how do I install using docker or build from source - HassoI Pi

### ISSUE THREAD

**Issue by markdswan926** [virtualzone/landroid-bridge#87]
Hi,

Newbie here struggling with new world.

The install notes talk about either installing using docker, or build from source.

I am unsure how to access docker, and when I try the build from source route i just get an unexpected indentifier error on the first line of code when entered into node.js (of which I understand nothing!)

I have searched for this basic help but without success. any pointers/patient assistance greatfully received

**Comment by riker09** [comment]
Hello @markdswan926, have you ever used Docker for anything? If not, you can head over to https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04 and follow these simple instuctions to get started with Docker on Ubuntu Linux.

I'm using the landroid-bridge on my QNAP NAS to monitor my Landroid-S mower. However, there is currently some issue and the bridge never connects. See ticket #88.
