### ISSUE TITLE
Running landroid-brigdge on Synology docker 

### ISSUE THREAD

**Issue by irqnet** [virtualzone/landroid-bridge#93]
Has anyone succesfully implemented the landroid bridge on synology docker?

I've tried to add it and the container started, but the webinterface didn't show anything, and the console output is not so meaningful.

Tried the following:

docker run -p 3000:3000 --name landroid_bridge -v /volume1/docker/landroid/config.json:/usr/src/app/config.json virtualzone/ landroid-bridge

console on synology:
![image](https://user-images.githubusercontent.com/32534199/77074471-324a8200-69f1-11ea-9c2f-e140770d011b.png)

protocol on synology:
![image](https://user-images.githubusercontent.com/32534199/77074486-37a7cc80-69f1-11ea-8003-60bb60894256.png)

web gui:

![image](https://user-images.githubusercontent.com/32534199/77074577-53ab6e00-69f1-11ea-907d-c63bed349d95.png)

What I changed is not to use the link to mqtt cause I'm using a broker running on a raspberry pi right now, but the landroid-brige is not going to connect to my broker respectively I'm not seeing any topics with MQTT explorer.

**Comment by debouttek** [comment]
Has to do with the API.
Look here:
https://github.com/virtualzone/landroid-bridge/issues/88
https://github.com/virtualzone/landroid-bridge/issues/90
